### ISSUE TITLE
Error during setup: 'pkg command not found'

### ISSUE THREAD

**Issue by dudewheresmycode** [Gobind03/mongo-analyser#1]
### Problem
The setup instructions assume you have `pkg` installed globally on the system. 

### To Reproduce
```bash
% npm run build-mac-intel

> mongo-analyser@1.0.0 build-mac-intel
> pkg -t node16-macos-x64 index.js -c package.json -o build/mongo-analyser-macos-x64

sh: pkg: command not found
```

### Solution

`pkg` should be added as a `devDependency` to the `package.json`

**Comment by Gobind03** [comment]
Fix pushed. Will be formally released in TS Refactored stable release.

Thank you :)
